// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_4owZslRigUchycr7EOOXZ7yVlcOdvWI',
    appId: '1:841575650656:web:013b40be14c8a16368fa05',
    messagingSenderId: '841575650656',
    projectId: 'cairo-cash-efeb8',
    authDomain: 'cairo-cash-efeb8.firebaseapp.com',
    storageBucket: 'cairo-cash-efeb8.appspot.com',
    measurementId: 'G-H92QQXH1V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3s3sKVsapbQcNYOaaB68MqP4n5sw_BU',
    appId: '1:841575650656:android:746975ef4043967868fa05',
    messagingSenderId: '841575650656',
    projectId: 'cairo-cash-efeb8',
    storageBucket: 'cairo-cash-efeb8.appspot.com',
  );
}
